config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'skills#index'
  get "/dashboard" => "dashboard#show"
  get "/bio" => "bio#index"

  resources :skills do
    resources :projects
  end

  resources :posts do
    resources :comments
  end

  resources :recommendations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  validates :comment_content, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  validates :post_title, :presence => true
  validates :post_content, :presence => true

  has_attached_file :attached_image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :attached_image, :content_type => /\Aimage\/.*\Z/
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :skill
  validates :project_name, :presence => true
  validates :project_short_description, :presence => true
  validates :project_full_description, :presence => true
  validates :project_link, :presence => true
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  validates :recommendation_content, :presence => true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :projects
  validates :skill_name, :presence => true
  validates :skill_full_description, :presence => true
  validates :skill_icon, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :username
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :username) }
  end
end

app/controllers/bio_controller.rb
class BioController < ApplicationController

  def index

  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.comment_author = current_user.username
    if @comment.save
      respond_to do |format|
        format.html { redirect_to post_url(@post) }
        format.js
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to posts_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:comment_content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_filter :authenticate_user!
  before_filter do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end

  def show
    @users = User.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    if current_user && current_user.admin?
      @post = Post.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post saved."
      redirect_to posts_path
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def edit
    if current_user && current_user.admin?
      @post = Post.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post updated."
      redirect_to posts_path
    else
      flash[:notice] = "Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:post_title, :post_content, :attached_image)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter do
    redirect_to new_user_session_path unless current_user && current_user.admin?
  end

  def new
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new
  end

  def create
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.new(project_params)
    if @project.save
      flash[:notice] = "Your project has been added."
      redirect_to skill_path(@skill.id)
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def show
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.find(params[:id])
  end

  def edit
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Your project has been updated."
      redirect_to skill_path(@skill.id)
    else
      flash[:notice] = "Please try again."
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:skill_id])
    @project = @skill.projects.find(params[:id])
    @project.destroy
    redirect_to skill_path(@skill)
  end

  private
  def project_params
    params.require(:project).permit(:project_name, :project_short_description, :project_full_description, :project_link, :project_image_url)
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController

  def index
    @recommendations = Recommendation.all
  end

  def new
    @recommendation = Recommendation.new
  end

  def create
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.recommendation_author = current_user.username
    if @recommendation.save
      respond_to do |format|
        format.html { redirect_to skills_url }
        format.js
      end
    end
  end

  def destroy
  end

  private
  def recommendation_params
    params.require(:recommendation).permit(:recommendation_content)
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index
    @skills = Skill.order(:skill_name)
  end

  def new
    if current_user && current_user.admin?
      @skill = Skill.new
    else
      redirect_to new_user_session_path
    end
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      flash[:notice] = "Your skill has been saved."
      redirect_to root_path
    else
      flash[:notice] = "Please try again."
      render :new
    end
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def edit
    if current_user && current_user.admin?
      @skill = Skill.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skill_params)
      flash[:notice] = "Your edits have been saved."
      redirect_to skill_path(@skill)
    else
      flash[:notice] = "Please try again."
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to skills_path
  end

  private
  def skill_params
    params.require(:skill).permit(:skill_name, :skill_short_description, :skill_full_description, :skill_icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bio/index.html.erb
<div class="padding">
  <div id="bio">

    <%= image_tag("FranzProfilePic.JPG", id: "bio-pic", alt: 'Picture of me with baby son Leo.') %>

    <p>I'm a graduate of the Epicodus coding school in Portland, Oregon, where I learned Ruby, JavaScript, Ruby on Rails and Ember. I also have experience with html, css/sass, AJAX and sinatra. I use a wide range of Rails gems from devise and bcrypt (for authentication) to rspec, capybara and phantomjs (for testing). To see more of my code, check out my <a href="http://github.com/franzknupfer">Github</a>.</p>

    <p>I received my B.A. from the University of Iowa and my M.F.A. from Johns Hopkins University, and I also spent a year in Nepal on a Fulbright grant. My writing has been published in blogs, literary magazines, and other publications. To see more of my creative work, check out <a href="http://franzknupfer.github.io/">franzknupfer.github.io</a>.</p>

    <p>I live in Portland, Oregon, with my wife, baby son, and two cats.</p>
  </div>
</div>

app/views/comments/_form.html.erb
<div id="comments-form">
  <%= bootstrap_form_for [@post, @comment], remote: true do |f| %>
    <%= f.text_area :comment_content, label: "Add your comment" %>
    <%= f.submit "Add comment", class: "btn btn-success" %>
  <% end %>
</div>

app/views/comments/_length.html.erb
<div id="comments_length">
  <%= @post.comments.length %>
</div>

app/views/comments/create.js.erb
$('form').remove();
$('#comment-header').remove();
$('#new_comment_link_<%= @post.id %>').show();
$('#comments').append('<p><%= @comment.comment_content %><strong> -<%= @comment.comment_author %></strong></p>');
$('#lengthy').remove();
$('#length_<%= @post.id %>').hide().after('<div id="lengthy"><%= j render ("length") %></div>');

app/views/comments/new.html.erb
<%= render "form" %>

app/views/comments/new.js.erb
$('#new_comment_link_<%= @post.id %>').hide().after('<%= j render ("form") %>');

app/views/dashboard/show.html.erb
<div class="padding">
  <h1>Admin Dashboard</h1>

  <h3>Total Users: <%= @users.length %></h3>

  <h3>User contact information</h3>

  <% if @users.any? %>
    <% @users.each do |user| %>
      <p><%= user.username %>, <%= user.email %></p>
    <% end %>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors</h3>
  <% object.errors.full_messages.each do |message| %>
    <p><%= message %></p>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    This site powered by Ruby on Rails.
  </small>
  <nav>
    <ul>
      <li>franzknupfer@hotmail.com</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <a class="pull-left", href="/"><span id="logo"><%= image_tag("ninja-background.svg") %></span></a>
        <a href="/", class="navbar-brand">Franz Knupfer</a>
        <% if user_signed_in? %>
          <li class="navbar-right"><%= link_to current_user.username, edit_user_registration_path, id: "nav-element" %></a></li>
          <li class="navbar-right"><%= link_to "Sign out", destroy_user_session_path, method: :delete, id: "nav-element" %></li>
        <% else %>
          <li class="navbar-right"><%= link_to "Sign up", new_user_registration_path, id: "nav-element" %></li>
          <li class="navbar-right"><%= link_to "Sign in", new_user_session_path, id: "nav-element" %></li>
        <% end %>
        <li class="navbar-right"><%= link_to "About Me", bio_path, id: "nav-element" %></li>
        <li class="navbar-right"><%= link_to "Blog", posts_path, id: "nav-element" %></li>
        <% if user_signed_in? && current_user.admin? %>
          <li class="navbar-right"><%= link_to "Admin Dashboard", dashboard_path, id: "nav-element" %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href="//fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet" type="text/css">
  <link href='//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,400italic' rel='stylesheet' type='text/css'>
</head>
<%= render 'layouts/header' %>
<body>



<div class="container-fluid">

  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/posts/_comments.html.erb
<div id="comments_<%= @post.id %>">
  <div id="comments">
    <h4><%= link_to "Hide comments", posts_path, id: "hide_comments" %></h4>
    <% if @post.comments.any? %>
      <% if current_user && current_user.admin? %>
        <% @post.comments.each do |comment| %>
          <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong><%= link_to "X", post_comment_path(@post, comment),
          :data => {:confirm => "Are you sure you want to delete this comment?",
          :method => "delete"} %></p>
        <% end %>
      <% else %>
          <% @post.comments.each do |comment| %>
            <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong></p>
          <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="padding">
  <h1>Edit Blog Post</h1>

  <%= bootstrap_form_for @post do |f| %>
    <%= f.text_field :post_title %>
    <br><br>
    <%= f.text_area :post_content %>
    <br>
    <%= f.file_field :attached_image %>
    <br>
    <%= f.submit "Edit post", class: "btn btn-success" %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="padding">
  <div id="blog-index">
    <h1>Blog</h1>

    <% if current_user && current_user.admin? %>
      <%= link_to "New post", new_post_path %>
    <% end %>

    <% if @posts.any? %>
      <% @posts.each do |post| %>
        <div id="blog-title">
          <h3><%= link_to post.post_title, post_path(post) %></h3>
          <h4><%= post.created_at.time.strftime "%B %d, %Y" %></h4>
        </div>
        <%= image_tag post.attached_image.url(:medium), id: "blog-pic" %>
        <p><%= post.post_content %></p>

        <h4>Comments: <div id="length_<%= post.id %>"><%= post.comments.length %></h4></div>
        <h4><%= link_to "Show comments", post_path(post), id: "show_comments_link_#{ post.id }", remote: true  %></h4>
        <% if current_user %>
          <h4><%= link_to "Add a comment", new_post_comment_path(post), id: "new_comment_link_#{ post.id }", remote: true %></h4>
        <% else %>
          <p><%= link_to "Sign in to post comments.", new_user_session_path %></p>
        <% end %>
        <br>
      <% end %>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="padding">
  <h1>New Blog Post</h1>

  <%= bootstrap_form_for @post, :url => posts_path, :html => { :multipart => true} do |f| %>
    <%= f.text_field :post_title %>
    <br><br>
    <%= f.text_area :post_content %>
    <br>
    <%= f.file_field :attached_image %>
    <br>
    <%= f.submit "Add post", class: "btn btn-success" %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="padding">
  <div id="blog-title">
    <h1><%= @post.post_title %></h1>
    <h4><%= @post.created_at.time.strftime "%B %d, %Y" %></h4>
  </div>
  <%= image_tag @post.attached_image.url(:medium), id: "blog-pic" %>
  <p><%= @post.post_content %></p>

  <h3>Comments</h3>

  <% if current_user %>
    <%= link_to "Add a comment", new_post_comment_path(@post), id: "new_comment_link_#{ @post.id }", class: "btn btn-success", remote: true %>
  <% else %>
    <p><%= link_to "Sign in to post comments.", new_user_session_path %></p>
  <% end %>

  <div id="comments">
    <% if @post.comments.any? %>
      <% if current_user && current_user.admin? %>
        <% @post.comments.each do |comment| %>
          <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong><%= link_to "X", post_comment_path(@post, comment),
          :data => {:confirm => "Are you sure you want to delete this comment?",
          :method => "delete"} %></p>
        <% end %>
      <% else %>
          <% @post.comments.each do |comment| %>
            <p><%= comment.comment_content %>  <strong>-<%= comment.comment_author %></strong></p>
          <% end %>
      <% end %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.admin %>
      <p><%= link_to "Edit post", edit_post_path %></p>
      <p><%= link_to "Delete post", post_path(@post), :data => {:confirm => "Are you sure you want to delete this post?",
      :method => "delete"} %></p>
    <% end %>
  <% end %>
</div>

app/views/posts/show.js.erb
$('#show_comments_link_<%= @post.id %>').hide().after('<%= j render("comments") %>');

app/views/projects/_form.html.erb
<% render "layouts/errors", :object => @project %>

<%= bootstrap_form_for [@skill, @project] do |f| %>
  <%= f.text_field :project_name %>
  <br>
  <%= f.text_field :project_short_description, label: "A short description for specific skill show pages" %>
  <br>
  <%= f.text_field :project_full_description, label: "A longer description for the project show page" %>
  <br>
  <%= f.text_field :project_image_url, label: "Add a screen shot of the project" %>
  <br>
  <%= f.text_field :project_link, label: "Add a link to the project" %>
  <%= f.submit "Add project", class: "btn btn-success" %>
<% end %>
<br>
<%= link_to "Return to home page", skills_path %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

<p><%= link_to "Delete this project", skill_project_path(@skill, @project),
:data => {:confirm => "Are you sure you want to delete this project?",
:method => "delete"} %></p>

app/views/projects/new.html.erb
<h1>Add New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="profile">
  <img src="<%= @project.project_image_url %>">
  <h1><%= @project.project_name %></h1>
  <h4><%= @project.project_link %></h4>

  <h3><%= @project.project_short_description %></h3>

  <p><%= @project.project_full_description %></p>

  <p><%= link_to "Edit this project", edit_skill_project_path(@skill, @project) %></p>
  <p><%= link_to "Return to skill page", skill_path(@skill.id) %></p>
  <p><%= link_to "Return to home page", skills_path %></p>
</div>

app/views/recommendations/_best_of.html.erb
<div id="best_of">
  <h1>Best of Portland</h1>

  <p>This feature uses AJAX to automatically load content without reloading the page. Check out some of my favorite things about Portland. Sign in and add your favorites, too.</p>

  <% if current_user %>
    <%= link_to "Add a recommendation", new_recommendation_path, id: "new_recommendation_link", class: "btn btn-success", remote: true %>
  <% else %>
    <p><%= link_to "Sign in to add a recommendation", new_user_session_path %></p>
  <% end %>

  <h3>Recommendations</h3>
  <div id="recommendations">
    <% if @recommendations.any? %>
      <%= render(@recommendations) %>
    <% end %>
  </div>


  <%= link_to "Close", root_path, id: "hide_best_of", class: "btn btn-success" %>

app/views/recommendations/_form.html.erb
<div id="recommendation-header">
  <h3>Hey there, <%= current_user.username %>!</h3>
</div>

<%= bootstrap_form_for @recommendation, remote: true do |f| %>
  <%= f.text_area :recommendation_content, label: "What do you like about Portland?" %>
  <%= f.submit "Add recommendation", class: "btn btn-success" %>
<% end %>

app/views/recommendations/_recommendation.html.erb
<p><%= recommendation.recommendation_content %> -<%= recommendation.recommendation_author %></p>

app/views/recommendations/create.js.erb
$('form').hide();
$('#new_recommendation_link').show();
$('#recommendation-header').hide();
$('#recommendations').append('<%= j render (@recommendation) %>');

app/views/recommendations/index.html.erb
<%= render "best_of" %>

app/views/recommendations/index.js.erb
$('#best_of_link').hide().after('<%= j render("best_of") %>');

app/views/recommendations/new.js.erb
$('#new_recommendation_link').hide().after('<%= j render("form") %>');

app/views/skills/_form.html.erb
<% render "layouts/errors", :object => @skill %>

<%= bootstrap_form_for @skill do |f| %>
  <%= f.text_field :skill_name %>
  <br>
  <%= f.text_area :skill_full_description, label: "Describe this skill" %>
  <br>
  <%= f.text_field :skill_icon, label: "Add an icon" %>
  <br>
  <%= f.submit "Add skill", class: "btn btn-success" %>
<% end %>
<br>

<%= link_to "Return to home page", skills_path %>

app/views/skills/edit.html.erb
<h1>Edit skill</h1>

<%= render 'form' %>

<p><%= link_to 'Delete this skill', skill_path(@skill),
:data => {:confirm => "Are you sure you want to delete this skill?",
:method => "delete"} %></p>

app/views/skills/index.html.erb
  <div id="blended">
  </div>

<div id="home-page">
  <div class="container">

    <div class="row">
      <div id="header">
        <h1>Web Developer, Problem Solver, Creative Thinker.</h1>
        <br><br>

        <div id="welcome-box">
          <p>I'm a newly-minted web developer and long-term writer combining my skills as a focused and analytical problem-solver with my skills as a passionate creative type.</p>
          <p>Need help writing creative content or catchy tag lines on the front end? I can help with that. More focused on back-end problem-solving and TDD? I can offer that, too.</p>
        </div>
      </div>


      <% @skills.each do |skill| %>
        <div class="col-md-3">
          <div class="all-skills">
            <h4 id="centered"><%= link_to skill.skill_name, skill_path(skill), id:"skill-header" %></h4>
            <%= link_to image_tag(skill.skill_icon), skill_path(skill) %>
          </div>
        </div>
      <% end %>
    </div>
    <br><br>
    <% if current_user && current_user.admin? %>
      <h3 class="centered"><%= link_to "Add skill", new_skill_path %></h3>
    <% end %>
    <div class="centered">

      <p>Click on the button below to see AJAX functionality at work.</p>
      <p><%= link_to "Best of Portland", recommendations_path, id: "best_of_link", class: "btn btn-success", remote: true %></p>
      <br><br>

    </div>
  </div>
</div>

app/views/skills/new.html.erb
<h1>Add a skill</h1>

<%= render 'form' %>

app/views/skills/show.html.erb
<div class="padding">
  <div class="profile">
    <p><%= image_tag(@skill.skill_icon) %></p>
    <br>
    <p><%= @skill.skill_full_description %></p>


    <% if @skill.projects.any? %>
      <h3><%= @skill.skill_name %> Projects</h3>
      <% @skill.projects.each do |project| %>
        <h5><%= project.project_name %></h5>
        <p><%= project.project_link %></p>
        <p><%= project.project_full_description %>
        <% if current_user && current_user.admin? %>
          <%= link_to "Edit this project", edit_skill_project_path(@skill, project) %>
        <% end %>
      <% end %>
    <% end %>
    <br><br>

    <p><%= link_to "Return to home page", root_path %>

    <% if current_user && current_user.admin? %>
      <p><%= link_to "Add a project", new_skill_project_path(@skill) %>
      <p><%= link_to "Edit this skill", edit_skill_path(@skill) %>
    <% end %>
  </div>
</div>